# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCProjectTemplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'AFNetworking'
pod 'YYModel'
pod 'MJRefresh'
pod 'MBProgressHUD'

  # Pods for CCProjectTemplate

  target 'CCProjectTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CCProjectTemplateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
